### ISSUE TITLE
Work on Project Integration and Pull Requests

### ISSUE THREAD

**Issue by logan-giese** [logan-giese/whiteboard-course-management#89]
- [x] Review and fix #81 
- [x] Ensure #67 is resolved by merging #81
- [x] Review and integrate #84 (ensure styling/structure is merged successfully)
- [x] Review and merge other remaining pull requests (if possible)

**Comment by logan-giese** [comment]
All pull requests are reviewed and merged at last!  Still some styling issues from #84, but we went over our daily Firestore quota so I couldn't keep working on it.
